### PR TITLE
【Add】New article.

### PR DESCRIPTION
**Pull request by jpcie**
## Created new article
- Diagnostics-tools-for-App-Service-on-Linux-Node.js-apps

### CODE REVIEW

**Comment by georgeOsdDev** [comment]
Visit your site at: https://ashy-ocean-0b702d800-275.eastasia.3.azurestaticapps.net/

image

**Comment by georgeOsdDev** [comment]
https://github.com/Azure/static-web-apps/issues/797

**Comment by georgeOsdDev** [comment]
Below article may releated for "Unexectedly failed to add GitHub comment."
https://docs.opensource.microsoft.com/github/apps/permission-changes/

**Comment by jpcie** [comment]
@microsoft-github-policy-service agree

**Comment by jpcie** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Pull request merged**
